### ISSUE TITLE
**Error handling**

### ISSUE THREAD

**Issue by vsuaste** [ScienceDb/express_graphql_model_gen#16]
Should we determine our own error clasification and the messages displayed accordingly?
For the code-generators the erros should be only displayed in the console as a text message?
For the SPA how should we display errors? (maybe just as alerts )

**Comment by asishallab** [comment]
Needs to be specified in more detail as a card in the [respective project](https://github.com/orgs/ScienceDb/projects/1), not as a single Issue.
