### ISSUE TITLE
Syntactically wrong superfluous comma generated from attributes

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/express_graphql_model_gen#23]
Consider this input:
```
{
  "model" : "individual",
  "storageType" : "SQL",
  "attributes" : {
    "name" : "String"
  }
}
```
which generates this excerpt of the output:
```
[...]
  var individual = sequelize.define('individual', {
    name: {
      type: Sequelize.STRING
    },
[...]
```

Please note the comma after the declaration of the `name` attribute. As it is the _last_ attribute listed for the data model `individual` this comma is syntactically wrong. Future more strict versions of NodeJs might cause a syntax error here. Please fix. The code generator should know, when it arrived at the last attribute and in this case _not_ append a comma.

**Comment by vsuaste** [comment]
Fixed: views/create-migrations.ejs , views/create-models.ejs
