### ISSUE TITLE
Functions to fetch Sequelize based associations are named wrong, when associated model-name is given in lowercase

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/express_graphql_model_gen#24]
Consider the following example input
```
{
  "model" : "individual",
  "storageType" : "SQL",
  "attributes" : {
    "name" : "String"
  },
  "associations": {
    "transcript_counts": {
      "type" : "sql_hasMany",
      "target" : "transcript_count",
      "targetKey" : "individual_id",
      "targetStorageType" : "sql"
    }
  }
}
```

This generates the following excerpt of resolvers
```
[...]
return this.gettranscript_counts(options);
[...]
```

This is an _undefined_ function. Sequelize automatically assigns capitalized first letter getters for associated models. The correct spelling would be
```
return this.getTranscript_counts(options);
```

Fix by capitalizing the first letter of the associated model. Verify that this still works for model names given with a capital first letter, e.g. `Person`, or `Book`.

**Comment by vsuaste** [comment]
Model's name is also used to name functions when generating code. In order to have more homogeneous code, model's name will be capitalized internally (in particular target model's name).
Fixed:  parseAssociations in funks.js

**Comment by vsuaste** [comment]
Ok. 
Then I only have one suggestion. The model's name is also used to name functions when generating code, which meas that for example, if our model name is "book" then the functions to update, delete, create would be: "updatebook", "deletebook" ,"createbook" and I think is more readable if we name them: "updateBook", "deleteBook", "createBook" , which I would say is better under the naming conventions. 
We can leave the models name as indicated by the user(lower/upper case) for the graphql schema and sequlize model (somewhere else?).  But for naming the functions mentioned above we could use upper case. What do you think?

**Comment by vsuaste** [comment]
Fixed: [33bcb8](https://github.com/ScienceDb/express_graphql_model_gen/commit/33bcb867ee4c3184e39e0299767dc763868b81b8)
