### ISSUE TITLE
Rename search-argument in the generated GraphQL schemas from "input" to "searchArg"

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/express_graphql_model_gen#29]
Consider this example
```
type Query {
    individuals(input: searchIndividualInput, order: [ orderIndividualInput ], pagination: paginationInput ): [Individual]
  }
```
`input: searchIndividualInput` would much more suitably become 
`searchArg: searchIndividualInput` or something comparable equally talkative.

**Comment by vsuaste** [comment]
Done. Commit [#5b6868](https://github.com/ScienceDb/express_graphql_model_gen/commit/5b6868e16e420f2ed7c133891bd66ee62dd0a4ec)
