### ISSUE TITLE
Add a resolver to generate the JSON data object as vuetable-2 needs it

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/express_graphql_model_gen#31]
The single page application that builds on top of the web service GraphQL API uses vuetable-2 to generate the master table view for a given data model. Include a GrapqhQL resolver for each model that delivers the JSON data object as vuetable-2 needs it.

For the restful example resolver see:
* [helper.js line 174](https://github.com/ScienceDb/express_route_gen_js/blob/master/helper.js)
* [get_routes template from line 48](https://github.com/ScienceDb/express_route_gen_js/blob/master/views/pages/controller_get.ejs)

For the single page code generator see:
* [master table view](https://github.com/ScienceDb/admin_gui_gen/blob/master/views/pages/tableView.ejs)

**Comment by vsuaste** [comment]
Done. [#6ae09c](https://github.com/ScienceDb/express_graphql_model_gen/commit/6ae09cf6297a1fe3ba324ab4ff1a53808f420482)
[#16dc3f](https://github.com/ScienceDb/server-graphql-sequelize/commit/16dc3f9ee6963c8666acd5804603403fb48b456c)
